# Generated by Django 5.2.5 on 2025-08-27 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('skip_vote', models.BooleanField(default=False)),
                ('vote_time', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.election')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elections.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'candidate', 'election', 'vote_time')},
            },
        ),
    ]
