# Generated by Django 5.2.5 on 2025-08-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_action', models.CharField(choices=[('cast_vote', 'Cast Vote'), ('login', 'Login'), ('generate_token', 'Generate Token'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('description', models.TextField(blank=True)),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.voter')),
            ],
            options={
                'ordering': ['-log_time'],
            },
        ),
    ]
